version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-cache-{{ .Branch }}
      - run:
          name: install update
          command: sudo apt update
          no_output_timeout: 60m
      - run:
          name: install build-essential
          command: sudo apt install build-essential
          no_output_timeout: 60m
      - run:
          name: install node-gyp
          command: sudo yarn global add node-gyp
          no_output_timeout: 60m
      - run:
          name: install libavahi-common-dev
          command: sudo apt install libavahi-common-dev
          no_output_timeout: 60m
      - run:
          name: install libavahi-client-dev
          command: sudo apt install libavahi-client-dev
          no_output_timeout: 60m
      - run:
          name: Copy libndi files to /usr/lib/x86_64-linux-gnu
          command: sudo cp lib/x86_64-linux-gnu/* /usr/lib/x86_64-linux-gnu
      - run:
          name: yarn install
          command: yarn install --check-files #--frozen-lockfile
          no_output_timeout: 60m
      - run: yarn validate:dependencies
      - run:
          name: yarn build-server
          command: yarn build-server
          no_output_timeout: 60m
      - run:
          name: yarn build-client
          command: yarn build-client
          no_output_timeout: 60m
      - save_cache:
          key: v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save_cache:
          key: v3-node-cache-{{ .Branch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish-tag:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker:
          # docker_layer_caching: true
          version: 18.06.0-ce
      - attach_workspace:
          at: .
      - run:
          name: Build Docker Image
          command: docker build -f Dockerfile . -t olzzon/ndi-ember-mtx:$CIRCLE_TAG
      - run:
           name: Publish Docker Image to Docker Hub
           command: |
             if [ -z "$DOCKERHUB_PASS" ]; then
               echo "Skipping"
             else
               echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
               docker tag olzzon/ndi-ember-mtx:$CIRCLE_TAG $DOCKERHUB_IMAGE:$CIRCLE_TAG
               docker push $DOCKERHUB_IMAGE:$CIRCLE_TAG
             fi
      - run:
           name: Publish Docker Image to Github Package Registry
           command: |
             if [ -z "$GITHUB_PASS" ]; then
               echo "Skipping"
             else
               echo "$GITHUB_PASS" | docker login docker.pkg.github.com -u "$GITHUB_USERNAME" --password-stdin
               docker tag olzzon/ndi-ember-mtx:$CIRCLE_TAG docker.pkg.github.com/$GITHUB_IMAGE:$CIRCLE_TAG
               docker push docker.pkg.github.com/$GITHUB_IMAGE:$CIRCLE_TAG
             fi
  publish-branch:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker:
          # docker_layer_caching: true
          version: 18.06.0-ce
      - attach_workspace:
          at: .
      - run:
          name: Build Docker Image
          command: docker build -f Dockerfile . -t olzzon/ndi-ember-mtx:$CIRCLE_BRANCH
      - run:
           name: Publish Docker Image to Docker Hub
           command: |
             if [ -z "$DOCKERHUB_PASS" ]; then
               echo "Skipping"
             else
               echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
               docker tag olzzon/ndi-ember-mtx:$CIRCLE_BRANCH $DOCKERHUB_IMAGE:$CIRCLE_BRANCH
               docker push $DOCKERHUB_IMAGE:$CIRCLE_BRANCH
             fi
      - run:
           name: Publish Docker Image to Github Package Registry
           command: |
             if [ -z "$GITHUB_PASS" ]; then
               echo "Skipping"
             else
               echo "$GITHUB_PASS" | docker login docker.pkg.github.com -u "$GITHUB_USERNAME" --password-stdin
               docker tag olzzon/ndi-ember-mtx:$CIRCLE_BRANCH docker.pkg.github.com/$GITHUB_IMAGE:$CIRCLE_BRANCH
               docker push docker.pkg.github.com/$GITHUB_IMAGE:$CIRCLE_BRANCH
             fi


workflows:
  version: 2
  build-test-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/
            branches:
              only: /.*/
      - publish-tag:
          requires:
            - build
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
      - publish-branch:
          requires:
            - build
          filters:
            tags:
              ignore: /v.*/
            branches:
              only:
                - master
                - develop
                - stage
                - /release\d+/
